# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AceptanceRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('realized', models.BooleanField(default=False, verbose_name='Realizado')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('toDo', 'toDo'), ('doing', 'doing'), ('done', 'done')], default='toDo', max_length=20, validators=[djchoices.choices.ChoicesValidator({'doing': 'doing', 'done': 'done', 'toDo': 'toDo'})])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBacklogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('estimations', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('toDo', 'toDo'), ('doing', 'doing'), ('done', 'done')], default='toDo', max_length=20, validators=[djchoices.choices.ChoicesValidator({'doing': 'doing', 'done': 'done', 'toDo': 'toDo'})])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basico.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('toDo', 'toDo'), ('doing', 'doing'), ('done', 'done')], default='toDo', max_length=20, validators=[djchoices.choices.ChoicesValidator({'doing': 'doing', 'done': 'done', 'toDo': 'toDo'})])),
                ('initialDate', models.DateTimeField(verbose_name='Data inicial')),
                ('pbItem', models.ManyToManyField(null=True, to='basico.ProductBacklogItem', verbose_name='Product Backlog')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='pbItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basico.ProductBacklogItem'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basico.Sprint'),
        ),
        migrations.AddField(
            model_name='aceptancerequirement',
            name='pbItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basico.ProductBacklogItem'),
        ),
    ]
