# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='initialDate',
            field=models.DateField(verbose_name='Data inicial'),
        ),
    ]
